import type { Metadata } from 'next';
import { Geist, Geist_Mono, Arimo } from 'next/font/google';
import './globals.css';

const arimo = Arimo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // 필요한 굵기 선택
  variable: '--font-arimo', // CSS 변수 이름 설정
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arimo.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
